<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Clara Bowman">

<title>Lab3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lab3_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab3_files/libs/quarto-html/quarto.js"></script>
<script src="lab3_files/libs/quarto-html/popper.min.js"></script>
<script src="lab3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab3_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab3_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab3_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="lab3_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="lab3_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="lab3_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="lab3_files/libs/leaflet-1.3.1/leaflet.css" rel="stylesheet">
<script src="lab3_files/libs/leaflet-1.3.1/leaflet.js"></script>
<link href="lab3_files/libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">
<script src="lab3_files/libs/proj4-2.6.2/proj4.min.js"></script>
<script src="lab3_files/libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="lab3_files/libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">
<script src="lab3_files/libs/leaflet-binding-2.2.3/leaflet.js"></script>
<script src="lab3_files/libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="lab3_files/libs/leaflet-providers-plugin-2.2.3/leaflet-providers-plugin.js"></script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab3</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Clara Bowman </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaflet)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<section id="read-in-the-data" class="level3">
<h3 class="anchored" data-anchor-id="read-in-the-data"><strong>1. Read in the data</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>met <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"met_all.gz"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="check-dimensions" class="level3">
<h3 class="anchored" data-anchor-id="check-dimensions">2. Check Dimensions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(met)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2377343      30</code></pre>
</div>
</div>
<p>There are 2377343 rows and 30 columns</p>
</section>
<section id="look-at-all-the-variables" class="level3">
<h3 class="anchored" data-anchor-id="look-at-all-the-variables">3. Look at all the variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(met)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2377343 obs. of  30 variables:
 $ USAFID           : int  690150 690150 690150 690150 690150 690150 690150 690150 690150 690150 ...
 $ WBAN             : int  93121 93121 93121 93121 93121 93121 93121 93121 93121 93121 ...
 $ year             : int  2019 2019 2019 2019 2019 2019 2019 2019 2019 2019 ...
 $ month            : int  8 8 8 8 8 8 8 8 8 8 ...
 $ day              : int  1 1 1 1 1 1 1 1 1 1 ...
 $ hour             : int  0 1 2 3 4 5 6 7 8 9 ...
 $ min              : int  56 56 56 56 56 56 56 56 56 56 ...
 $ lat              : num  34.3 34.3 34.3 34.3 34.3 34.3 34.3 34.3 34.3 34.3 ...
 $ lon              : num  -116 -116 -116 -116 -116 ...
 $ elev             : int  696 696 696 696 696 696 696 696 696 696 ...
 $ wind.dir         : int  220 230 230 210 120 NA 320 10 320 350 ...
 $ wind.dir.qc      : chr  "5" "5" "5" "5" ...
 $ wind.type.code   : chr  "N" "N" "N" "N" ...
 $ wind.sp          : num  5.7 8.2 6.7 5.1 2.1 0 1.5 2.1 2.6 1.5 ...
 $ wind.sp.qc       : chr  "5" "5" "5" "5" ...
 $ ceiling.ht       : int  22000 22000 22000 22000 22000 22000 22000 22000 22000 22000 ...
 $ ceiling.ht.qc    : int  5 5 5 5 5 5 5 5 5 5 ...
 $ ceiling.ht.method: chr  "9" "9" "9" "9" ...
 $ sky.cond         : chr  "N" "N" "N" "N" ...
 $ vis.dist         : int  16093 16093 16093 16093 16093 16093 16093 16093 16093 16093 ...
 $ vis.dist.qc      : chr  "5" "5" "5" "5" ...
 $ vis.var          : chr  "N" "N" "N" "N" ...
 $ vis.var.qc       : chr  "5" "5" "5" "5" ...
 $ temp             : num  37.2 35.6 34.4 33.3 32.8 31.1 29.4 28.9 27.2 26.7 ...
 $ temp.qc          : chr  "5" "5" "5" "5" ...
 $ dew.point        : num  10.6 10.6 7.2 5 5 5.6 6.1 6.7 7.8 7.8 ...
 $ dew.point.qc     : chr  "5" "5" "5" "5" ...
 $ atm.press        : num  1010 1010 1011 1012 1013 ...
 $ atm.press.qc     : int  5 5 5 5 5 5 5 5 5 5 ...
 $ rh               : num  19.9 21.8 18.5 16.9 17.4 ...</code></pre>
</div>
</div>
</section>
<section id="closer-look-at-key-variables" class="level3">
<h3 class="anchored" data-anchor-id="closer-look-at-key-variables">4. Closer Look at Key Variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(met[,<span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'day'</span>,<span class="st">'hour'</span>, <span class="st">'temp'</span>, <span class="st">'elev'</span>, <span class="st">'wind.sp'</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      year           day          hour            temp             elev       
 Min.   :2019   Min.   : 1   Min.   : 0.00   Min.   :-40.00   Min.   : -13.0  
 1st Qu.:2019   1st Qu.: 8   1st Qu.: 5.00   1st Qu.: 19.60   1st Qu.: 101.0  
 Median :2019   Median :16   Median :11.00   Median : 23.50   Median : 252.0  
 Mean   :2019   Mean   :16   Mean   :11.34   Mean   : 23.59   Mean   : 415.8  
 3rd Qu.:2019   3rd Qu.:24   3rd Qu.:17.00   3rd Qu.: 27.80   3rd Qu.: 400.0  
 Max.   :2019   Max.   :31   Max.   :23.00   Max.   : 56.00   Max.   :9999.0  
                                             NA's   :60089                    
    wind.sp      
 Min.   : 0.000  
 1st Qu.: 0.000  
 Median : 2.100  
 Mean   : 2.459  
 3rd Qu.: 3.600  
 Max.   :36.000  
 NA's   :79693   </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>met<span class="sc">$</span>elev[met<span class="sc">$</span>elev <span class="sc">==</span> <span class="dv">9999</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(met<span class="sc">$</span>elev)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    -13     101     252     413     400    4113     710 </code></pre>
</div>
</div>
<p>The highest elevation is at 4113</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>met<span class="sc">$</span>temp[met<span class="sc">$</span>temp <span class="sc">==</span> <span class="sc">-</span><span class="dv">40</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>met <span class="ot">&lt;-</span> met[<span class="sc">!</span><span class="fu">is.na</span>(met<span class="sc">$</span>temp),]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(met<span class="sc">$</span>temp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -17.20   19.60   23.50   23.59   27.80   56.00 </code></pre>
</div>
</div>
</section>
<section id="check-data" class="level3">
<h3 class="anchored" data-anchor-id="check-data">5. Check Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>low_temp <span class="ot">&lt;-</span> met[met<span class="sc">$</span>temp <span class="sc">&lt;</span> <span class="sc">-</span><span class="dv">10</span>,<span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'month'</span>,<span class="st">'day'</span>,<span class="st">'temp'</span>,<span class="st">'lon'</span>,<span class="st">'lat'</span>)]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>low_temp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        year month day  temp      lon    lat
1105455 2019     8  11 -17.0  -98.052 27.901
1105457 2019     8  12 -17.0  -98.052 27.901
1105459 2019     8  12 -17.0  -98.052 27.901
1203053 2019     8   1 -17.2 -104.300 38.767
1203054 2019     8   1 -17.0 -104.300 38.767
1203055 2019     8   1 -17.2 -104.300 38.767
1203128 2019     8   3 -17.2 -104.300 38.767
1203129 2019     8   3 -17.2 -104.300 38.767
1203221 2019     8   6 -17.0 -104.300 38.767
1203222 2019     8   6 -17.2 -104.300 38.767
1203223 2019     8   6 -17.0 -104.300 38.767
1203224 2019     8   6 -17.0 -104.300 38.767
1203225 2019     8   6 -17.2 -104.300 38.767
1203226 2019     8   6 -17.0 -104.300 38.767</code></pre>
</div>
</div>
<p>-17.2 was recorded in August 2019 at (38.767, -104.3) for several days. This is in the desert in Colorado where the record low ever was -8˚F, so -17.2 is impossible. The other weather station recording -17˚ is in Southern Texas where such low temperatures in Texas are not possible</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>co <span class="ot">&lt;-</span> met[met<span class="sc">$</span>lon <span class="sc">==</span> <span class="sc">-</span><span class="fl">104.300</span>,<span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'month'</span>,<span class="st">'day'</span>,<span class="st">'temp'</span>,<span class="st">'lon'</span>,<span class="st">'lat'</span>)]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>co</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        year month day  temp    lon    lat
1203053 2019     8   1 -17.2 -104.3 38.767
1203054 2019     8   1 -17.0 -104.3 38.767
1203055 2019     8   1 -17.2 -104.3 38.767
1203128 2019     8   3 -17.2 -104.3 38.767
1203129 2019     8   3 -17.2 -104.3 38.767
1203221 2019     8   6 -17.0 -104.3 38.767
1203222 2019     8   6 -17.2 -104.3 38.767
1203223 2019     8   6 -17.0 -104.3 38.767
1203224 2019     8   6 -17.0 -104.3 38.767
1203225 2019     8   6 -17.2 -104.3 38.767
1203226 2019     8   6 -17.0 -104.3 38.767
1203252 2019     8  12  16.2 -104.3 38.750
1203253 2019     8  12  17.5 -104.3 38.750
1203254 2019     8  12  16.2 -104.3 38.750
1203255 2019     8  12  16.2 -104.3 38.750
1203256 2019     8  12  15.7 -104.3 38.750
1203257 2019     8  12  13.1 -104.3 38.750
1203258 2019     8  12  12.8 -104.3 38.750
1203259 2019     8  12  13.4 -104.3 38.750
1203260 2019     8  12  12.7 -104.3 38.750
1203261 2019     8  12  14.4 -104.3 38.750
1203262 2019     8  12  19.8 -104.3 38.750
1203263 2019     8  12  24.8 -104.3 38.750
1203264 2019     8  12  26.9 -104.3 38.750
1203265 2019     8  12  27.6 -104.3 38.750
1203266 2019     8  12  28.3 -104.3 38.750
1203267 2019     8  12  28.9 -104.3 38.750
1203268 2019     8  12  28.1 -104.3 38.750
1203269 2019     8  12  29.0 -104.3 38.750
1203270 2019     8  12  28.4 -104.3 38.767
1203271 2019     8  12  28.9 -104.3 38.767
1203272 2019     8  12  27.1 -104.3 38.767
1203273 2019     8  13  26.4 -104.3 38.750
1203274 2019     8  13  26.0 -104.3 38.750
1203275 2019     8  13  25.0 -104.3 38.750
1203276 2019     8  13  24.4 -104.3 38.750
1203277 2019     8  13  21.8 -104.3 38.767
1203278 2019     8  13  20.2 -104.3 38.750
1203279 2019     8  13  19.3 -104.3 38.750
1203280 2019     8  13  18.5 -104.3 38.767
1203281 2019     8  13  17.7 -104.3 38.767
1203283 2019     8  13  15.8 -104.3 38.767
1203284 2019     8  13  13.8 -104.3 38.767
1203285 2019     8  13  12.6 -104.3 38.767
1203286 2019     8  13  14.4 -104.3 38.767
1203287 2019     8  13  12.3 -104.3 38.767
1203288 2019     8  13  14.2 -104.3 38.767
1203289 2019     8  13  19.0 -104.3 38.767
1203290 2019     8  13  22.5 -104.3 38.767
1203291 2019     8  13  23.8 -104.3 38.767
1203292 2019     8  13  26.2 -104.3 38.767
1203293 2019     8  13  27.8 -104.3 38.767
1203294 2019     8  13  29.2 -104.3 38.767
1203295 2019     8  13  28.0 -104.3 38.750
1203296 2019     8  13  28.0 -104.3 38.750
1203297 2019     8  13  28.2 -104.3 38.767
1203298 2019     8  13  29.6 -104.3 38.767
1203299 2019     8  13  28.2 -104.3 38.767
1203300 2019     8  13  28.0 -104.3 38.750
1203301 2019     8  13  28.0 -104.3 38.750
1203302 2019     8  13  27.0 -104.3 38.750
1203303 2019     8  13  25.0 -104.3 38.750
1203304 2019     8  13  24.0 -104.3 38.750
1203305 2019     8  13  23.0 -104.3 38.750
1203306 2019     8  13  20.0 -104.3 38.750
1203307 2019     8  13  21.0 -104.3 38.767
1203308 2019     8  14  21.0 -104.3 38.750
1203309 2019     8  14  22.0 -104.3 38.750
1203310 2019     8  14  25.0 -104.3 38.750
1203311 2019     8  14  24.0 -104.3 38.750
1203312 2019     8  14  24.0 -104.3 38.750
1203313 2019     8  14  24.0 -104.3 38.750
1203314 2019     8  14  23.7 -104.3 38.767
1203315 2019     8  14  23.0 -104.3 38.750
1203316 2019     8  14  24.0 -104.3 38.750
1203317 2019     8  14  24.0 -104.3 38.750
1203318 2019     8  14  21.1 -104.3 38.767
1203319 2019     8  14  21.0 -104.3 38.750
1203320 2019     8  14  21.0 -104.3 38.750
1203321 2019     8  14  16.1 -104.3 38.767
1203322 2019     8  14  16.0 -104.3 38.767
1203323 2019     8  14  15.7 -104.3 38.767
1203324 2019     8  14  15.0 -104.3 38.750
1203325 2019     8  14  16.0 -104.3 38.750
1203326 2019     8  14  15.7 -104.3 38.767
1203327 2019     8  14  14.5 -104.3 38.767
1203329 2019     8  14  14.0 -104.3 38.750
1203330 2019     8  14  14.6 -104.3 38.767
1203331 2019     8  14  15.0 -104.3 38.750
1203332 2019     8  14  15.1 -104.3 38.767
1203333 2019     8  14  15.0 -104.3 38.750
1203334 2019     8  14  15.0 -104.3 38.750
1203335 2019     8  14  14.0 -104.3 38.750
1203336 2019     8  14  14.0 -104.3 38.767
1203337 2019     8  14  13.0 -104.3 38.750
1203338 2019     8  14  13.3 -104.3 38.767
1203339 2019     8  14  13.0 -104.3 38.750
1203340 2019     8  14  13.9 -104.3 38.767
1203341 2019     8  14  14.0 -104.3 38.750
1203342 2019     8  14  14.0 -104.3 38.750
1203343 2019     8  14  13.8 -104.3 38.767
1203344 2019     8  14  14.2 -104.3 38.767
1203345 2019     8  14  14.0 -104.3 38.750
1203346 2019     8  14  15.0 -104.3 38.750
1203347 2019     8  14  15.5 -104.3 38.767
1203348 2019     8  14  16.7 -104.3 38.767
1203349 2019     8  14  19.0 -104.3 38.767
1203350 2019     8  14  19.0 -104.3 38.750
1203351 2019     8  14  21.5 -104.3 38.767
1203352 2019     8  14  23.7 -104.3 38.767
1203353 2019     8  14  23.0 -104.3 38.767
1203354 2019     8  14  25.2 -104.3 38.767
1203355 2019     8  14  26.5 -104.3 38.767
1203356 2019     8  14  26.5 -104.3 38.767
1203357 2019     8  15  25.0 -104.3 38.750
1203358 2019     8  15  26.0 -104.3 38.750
1203359 2019     8  15  26.2 -104.3 38.767
1203360 2019     8  15  21.5 -104.3 38.767
1203361 2019     8  15  18.8 -104.3 38.767
1203362 2019     8  15  20.2 -104.3 38.767
1203363 2019     8  15  17.5 -104.3 38.767
1203364 2019     8  15  16.9 -104.3 38.767
1203365 2019     8  15  15.6 -104.3 38.767
1203367 2019     8  15  14.8 -104.3 38.767
1203368 2019     8  15  13.5 -104.3 38.767
1203369 2019     8  15  11.1 -104.3 38.767
1203370 2019     8  15  11.0 -104.3 38.767
1203371 2019     8  15  11.3 -104.3 38.767
1203372 2019     8  15  13.9 -104.3 38.767
1203373 2019     8  15  19.9 -104.3 38.767
1203374 2019     8  15  24.6 -104.3 38.767
1203375 2019     8  15  29.1 -104.3 38.767
1203376 2019     8  15  29.6 -104.3 38.767
1203377 2019     8  15  30.1 -104.3 38.767
1203378 2019     8  15  30.4 -104.3 38.767
1203379 2019     8  15  32.0 -104.3 38.750
1203380 2019     8  15  32.0 -104.3 38.750
1203381 2019     8  15  32.2 -104.3 38.767
1203382 2019     8  15  31.0 -104.3 38.750
1203383 2019     8  15  31.5 -104.3 38.767
1203384 2019     8  15  32.3 -104.3 38.767
1203385 2019     8  15  32.0 -104.3 38.750
1203386 2019     8  15  32.0 -104.3 38.750
1203387 2019     8  15  32.0 -104.3 38.750
1203388 2019     8  15  31.0 -104.3 38.750
1203389 2019     8  15  30.1 -104.3 38.767
1203390 2019     8  15  30.0 -104.3 38.750
1203391 2019     8  15  30.0 -104.3 38.750
1203392 2019     8  15  28.9 -104.3 38.767
1203393 2019     8  16  28.5 -104.3 38.767
1203394 2019     8  16  24.9 -104.3 38.767
1203395 2019     8  16  23.6 -104.3 38.767
1203396 2019     8  16  21.7 -104.3 38.767
1203397 2019     8  16  20.8 -104.3 38.767
1203398 2019     8  16  19.9 -104.3 38.767
1203399 2019     8  16  17.6 -104.3 38.767
1203401 2019     8  16  16.3 -104.3 38.767
1203402 2019     8  16  13.2 -104.3 38.767
1203403 2019     8  16  14.7 -104.3 38.767
1203404 2019     8  16  12.6 -104.3 38.767
1203405 2019     8  16  10.8 -104.3 38.767
1203406 2019     8  16  11.7 -104.3 38.767
1203407 2019     8  16  18.3 -104.3 38.767
1203408 2019     8  16  21.8 -104.3 38.767
1203409 2019     8  16  23.9 -104.3 38.767
1203410 2019     8  16  25.9 -104.3 38.767
1203411 2019     8  16  28.0 -104.3 38.750
1203412 2019     8  16  28.8 -104.3 38.767
1203413 2019     8  16  30.3 -104.3 38.767
1203414 2019     8  16  30.5 -104.3 38.767
1203415 2019     8  16  30.0 -104.3 38.750
1203416 2019     8  16  32.4 -104.3 38.767
1203417 2019     8  16  33.0 -104.3 38.750
1203418 2019     8  16  34.0 -104.3 38.750
1203419 2019     8  16  33.9 -104.3 38.767
1203420 2019     8  16  31.0 -104.3 38.750
1203421 2019     8  16  31.0 -104.3 38.750
1203422 2019     8  16  31.0 -104.3 38.750
1203423 2019     8  16  30.0 -104.3 38.750
1203424 2019     8  16  29.8 -104.3 38.767
1203425 2019     8  16  30.0 -104.3 38.750
1203426 2019     8  16  27.4 -104.3 38.767
1203427 2019     8  17  24.2 -104.3 38.767
1203428 2019     8  17  21.1 -104.3 38.767
1203429 2019     8  17  19.0 -104.3 38.767
1203430 2019     8  17  18.6 -104.3 38.767
1203431 2019     8  17  18.8 -104.3 38.767
1203432 2019     8  17  17.5 -104.3 38.767
1203433 2019     8  17  17.3 -104.3 38.767
1203435 2019     8  17  16.6 -104.3 38.767
1203436 2019     8  17  15.7 -104.3 38.767
1203437 2019     8  17  16.1 -104.3 38.767
1203438 2019     8  17  14.2 -104.3 38.767
1203439 2019     8  17  11.2 -104.3 38.767
1203440 2019     8  17  11.4 -104.3 38.767
1203441 2019     8  17  17.6 -104.3 38.767
1203442 2019     8  17  20.6 -104.3 38.767
1203443 2019     8  17  23.3 -104.3 38.767
1203444 2019     8  17  27.1 -104.3 38.767
1203445 2019     8  17  29.7 -104.3 38.767
1203446 2019     8  17  31.0 -104.3 38.767
1203447 2019     8  17  32.0 -104.3 38.750
1203448 2019     8  17  32.0 -104.3 38.750
1203449 2019     8  17  32.2 -104.3 38.767
1203450 2019     8  17  34.0 -104.3 38.750
1203451 2019     8  17  32.0 -104.3 38.750
1203452 2019     8  17  32.0 -104.3 38.750
1203453 2019     8  17  33.0 -104.3 38.750
1203454 2019     8  17  31.6 -104.3 38.767
1203455 2019     8  17  32.0 -104.3 38.750
1203456 2019     8  17  32.0 -104.3 38.750
1203457 2019     8  17  32.0 -104.3 38.750
1203458 2019     8  17  31.0 -104.3 38.750
1203459 2019     8  17  28.5 -104.3 38.767
1203460 2019     8  17  27.5 -104.3 38.767
1203461 2019     8  17  26.4 -104.3 38.767
1203462 2019     8  18  25.3 -104.3 38.767
1203463 2019     8  18  22.3 -104.3 38.767
1203464 2019     8  18  21.1 -104.3 38.767
1203465 2019     8  18  18.7 -104.3 38.767
1203466 2019     8  18  17.7 -104.3 38.767
1203467 2019     8  18  17.9 -104.3 38.767
1203468 2019     8  18  13.4 -104.3 38.767
1203469 2019     8  18  11.3 -104.3 38.767
1203470 2019     8  18  12.5 -104.3 38.767
1203471 2019     8  18  11.4 -104.3 38.767
1203472 2019     8  18  12.4 -104.3 38.767
1203473 2019     8  18  10.8 -104.3 38.767
1203474 2019     8  18  13.9 -104.3 38.767
1203475 2019     8  18  21.0 -104.3 38.767
1203476 2019     8  18  23.2 -104.3 38.767
1203477 2019     8  18  24.9 -104.3 38.767
1203478 2019     8  18  26.0 -104.3 38.767
1203479 2019     8  18  27.7 -104.3 38.767
1203480 2019     8  18  29.0 -104.3 38.750
1203481 2019     8  18  29.3 -104.3 38.767
1203482 2019     8  18  30.9 -104.3 38.767
1203483 2019     8  18  32.0 -104.3 38.750
1203484 2019     8  18  31.7 -104.3 38.767
1203485 2019     8  18  32.0 -104.3 38.750
1203486 2019     8  18  32.0 -104.3 38.750
1203487 2019     8  18  32.7 -104.3 38.767
1203488 2019     8  18  32.6 -104.3 38.767
1203489 2019     8  18  33.0 -104.3 38.750
1203490 2019     8  18  32.0 -104.3 38.767
1203491 2019     8  19  29.1 -104.3 38.767
1203492 2019     8  19  25.8 -104.3 38.767
1203493 2019     8  19  23.8 -104.3 38.767
1203494 2019     8  19  22.2 -104.3 38.767
1203495 2019     8  19  20.8 -104.3 38.767
1203496 2019     8  19  19.4 -104.3 38.767
1203497 2019     8  19  19.3 -104.3 38.767
1203498 2019     8  19  18.2 -104.3 38.767
1203499 2019     8  19  17.1 -104.3 38.767
1203500 2019     8  19  14.4 -104.3 38.767
1203501 2019     8  19  11.6 -104.3 38.767
1203502 2019     8  19  10.8 -104.3 38.767
1203503 2019     8  19  13.0 -104.3 38.767
1203504 2019     8  19  21.8 -104.3 38.767
1203505 2019     8  19  27.2 -104.3 38.767
1203506 2019     8  19  27.7 -104.3 38.767
1203507 2019     8  19  30.8 -104.3 38.767
1203508 2019     8  19  32.2 -104.3 38.767
1203509 2019     8  19  31.8 -104.3 38.767
1203510 2019     8  19  32.0 -104.3 38.767
1203511 2019     8  19  33.2 -104.3 38.767
1203512 2019     8  19  32.9 -104.3 38.767
1203513 2019     8  20  32.4 -104.3 38.767
1203514 2019     8  20  26.3 -104.3 38.767
1203515 2019     8  20  17.7 -104.3 38.767
1203516 2019     8  20  17.6 -104.3 38.767
1203517 2019     8  20  17.2 -104.3 38.767
1203518 2019     8  20  17.2 -104.3 38.767
1203519 2019     8  20  19.6 -104.3 38.767
1203520 2019     8  20  24.9 -104.3 38.767
1203521 2019     8  20  27.2 -104.3 38.767
1203522 2019     8  20  27.7 -104.3 38.767
1203523 2019     8  20  29.7 -104.3 38.767
1203524 2019     8  20  32.0 -104.3 38.767
1203525 2019     8  20  32.6 -104.3 38.767
1203526 2019     8  20  33.5 -104.3 38.767
1203527 2019     8  20  33.6 -104.3 38.767
1203528 2019     8  20  32.9 -104.3 38.767
1203529 2019     8  20  32.9 -104.3 38.767
1203530 2019     8  20  33.4 -104.3 38.767
1203531 2019     8  21  30.8 -104.3 38.767
1203532 2019     8  21  30.0 -104.3 38.750
1203533 2019     8  21  30.0 -104.3 38.750
1203534 2019     8  21  29.0 -104.3 38.750
1203535 2019     8  21  27.0 -104.3 38.750
1203536 2019     8  21  27.5 -104.3 38.767
1203537 2019     8  21  24.1 -104.3 38.767
1203538 2019     8  21  25.0 -104.3 38.750
1203539 2019     8  21  26.0 -104.3 38.750
1203540 2019     8  21  27.0 -104.3 38.750
1203541 2019     8  21  26.9 -104.3 38.767
1203542 2019     8  21  25.0 -104.3 38.750
1203543 2019     8  21  24.0 -104.3 38.750
1203544 2019     8  21  24.0 -104.3 38.750
1203545 2019     8  21  24.0 -104.3 38.750
1203546 2019     8  21  24.2 -104.3 38.767
1203547 2019     8  21  22.7 -104.3 38.767
1203548 2019     8  21  25.0 -104.3 38.750
1203549 2019     8  21  26.0 -104.3 38.750
1203550 2019     8  21  25.6 -104.3 38.767
1203552 2019     8  21  23.7 -104.3 38.767
1203553 2019     8  21  21.8 -104.3 38.767
1203554 2019     8  21  22.0 -104.3 38.750
1203555 2019     8  21  17.2 -104.3 38.767
1203556 2019     8  21  16.8 -104.3 38.767
1203557 2019     8  21  16.0 -104.3 38.767
1203558 2019     8  21  16.0 -104.3 38.750
1203559 2019     8  21  16.0 -104.3 38.750
1203560 2019     8  21  16.0 -104.3 38.750
1203561 2019     8  21  15.6 -104.3 38.767
1203562 2019     8  21  16.0 -104.3 38.750
1203563 2019     8  21  17.3 -104.3 38.767
1203564 2019     8  21  19.6 -104.3 38.767
1203565 2019     8  21  22.0 -104.3 38.750
1203566 2019     8  21  21.6 -104.3 38.767
1203567 2019     8  21  22.7 -104.3 38.767
1203568 2019     8  21  24.0 -104.3 38.767
1203569 2019     8  21  25.2 -104.3 38.767
1203570 2019     8  21  26.4 -104.3 38.767
1203571 2019     8  21  26.6 -104.3 38.767
1203572 2019     8  21  25.5 -104.3 38.767
1203573 2019     8  21  24.9 -104.3 38.767
1203574 2019     8  21  25.0 -104.3 38.750
1203575 2019     8  21  23.0 -104.3 38.750
1203576 2019     8  21  23.5 -104.3 38.767
1203577 2019     8  22  22.3 -104.3 38.767
1203578 2019     8  22  20.3 -104.3 38.767
1203579 2019     8  22  19.1 -104.3 38.767
1203580 2019     8  22  18.0 -104.3 38.767
1203581 2019     8  22  17.6 -104.3 38.767
1203582 2019     8  22  17.9 -104.3 38.767
1203583 2019     8  22  16.7 -104.3 38.767
1203585 2019     8  22  15.6 -104.3 38.767
1203586 2019     8  22  16.0 -104.3 38.750
1203587 2019     8  22  16.0 -104.3 38.750
1203588 2019     8  22  16.0 -104.3 38.767
1203589 2019     8  22  16.0 -104.3 38.750
1203590 2019     8  22  16.6 -104.3 38.767
1203591 2019     8  22  17.0 -104.3 38.750
1203592 2019     8  22  16.0 -104.3 38.750
1203593 2019     8  22  14.8 -104.3 38.767
1203594 2019     8  22  11.9 -104.3 38.767
1203595 2019     8  22  12.0 -104.3 38.750
1203596 2019     8  22  13.0 -104.3 38.750
1203597 2019     8  22  13.3 -104.3 38.767
1203598 2019     8  22  17.9 -104.3 38.767
1203599 2019     8  22  19.8 -104.3 38.767
1203600 2019     8  22  22.1 -104.3 38.767
1203601 2019     8  22  24.4 -104.3 38.767
1203602 2019     8  22  25.0 -104.3 38.750
1203603 2019     8  22  24.5 -104.3 38.767
1203604 2019     8  22  26.1 -104.3 38.767
1203605 2019     8  22  27.0 -104.3 38.750
1203606 2019     8  22  28.0 -104.3 38.767
1203607 2019     8  22  29.0 -104.3 38.750
1203608 2019     8  22  28.1 -104.3 38.767
1203609 2019     8  22  27.5 -104.3 38.767
1203610 2019     8  22  27.4 -104.3 38.767
1203611 2019     8  22  26.1 -104.3 38.767
1203612 2019     8  22  25.0 -104.3 38.750
1203613 2019     8  23  23.0 -104.3 38.750
1203614 2019     8  23  23.0 -104.3 38.750
1203615 2019     8  23  22.0 -104.3 38.750
1203616 2019     8  23  17.0 -104.3 38.750
1203617 2019     8  23  17.7 -104.3 38.767
1203618 2019     8  23  19.0 -104.3 38.750
1203619 2019     8  23  19.0 -104.3 38.750
1203620 2019     8  23  19.0 -104.3 38.750
1203621 2019     8  23  19.0 -104.3 38.750
1203622 2019     8  23  19.0 -104.3 38.750
1203623 2019     8  23  21.0 -104.3 38.750
1203624 2019     8  23  23.0 -104.3 38.750
1203625 2019     8  23  23.0 -104.3 38.750
1203626 2019     8  23  23.0 -104.3 38.750
1203627 2019     8  23  23.8 -104.3 38.767
1203628 2019     8  23  20.4 -104.3 38.767
1203629 2019     8  23  20.1 -104.3 38.767
1203630 2019     8  23  21.5 -104.3 38.767
1203631 2019     8  23  20.0 -104.3 38.750
1203632 2019     8  23  20.0 -104.3 38.750
1203633 2019     8  23  19.5 -104.3 38.767
1203634 2019     8  23  16.3 -104.3 38.767
1203636 2019     8  23  16.2 -104.3 38.767
1203637 2019     8  23  15.1 -104.3 38.767
1203638 2019     8  23  14.1 -104.3 38.767
1203639 2019     8  23  14.1 -104.3 38.767
1203640 2019     8  23  14.8 -104.3 38.767
1203641 2019     8  23  13.3 -104.3 38.767
1203642 2019     8  23  18.4 -104.3 38.767
1203643 2019     8  23  20.6 -104.3 38.767
1203644 2019     8  23  22.9 -104.3 38.767
1203645 2019     8  23  24.4 -104.3 38.767
1203646 2019     8  23  26.7 -104.3 38.767
1203647 2019     8  23  28.0 -104.3 38.750
1203648 2019     8  23  28.0 -104.3 38.767
1203649 2019     8  23  26.8 -104.3 38.767
1203650 2019     8  23  26.5 -104.3 38.767
1203651 2019     8  23  27.0 -104.3 38.750
1203652 2019     8  23  24.6 -104.3 38.767
1203653 2019     8  23  24.0 -104.3 38.750
1203654 2019     8  23  24.0 -104.3 38.750
1203655 2019     8  23  23.0 -104.3 38.750
1203656 2019     8  23  15.0 -104.3 38.750
1203657 2019     8  23  15.0 -104.3 38.750
1203658 2019     8  23  16.0 -104.3 38.750
1203659 2019     8  23  18.0 -104.3 38.750
1203660 2019     8  23  18.0 -104.3 38.750
1203661 2019     8  23  17.7 -104.3 38.767
1203662 2019     8  24  19.0 -104.3 38.750
1203663 2019     8  24  18.6 -104.3 38.767
1203664 2019     8  24  19.0 -104.3 38.767
1203665 2019     8  24  14.6 -104.3 38.767
1203666 2019     8  24  13.8 -104.3 38.767
1203667 2019     8  24  14.6 -104.3 38.767
1203668 2019     8  24  14.6 -104.3 38.767
1203669 2019     8  24  14.0 -104.3 38.750
1203670 2019     8  24  15.0 -104.3 38.750
1203671 2019     8  24  15.0 -104.3 38.750
1203672 2019     8  24  14.8 -104.3 38.767
1203674 2019     8  24  15.0 -104.3 38.750
1203675 2019     8  24  14.7 -104.3 38.767
1203676 2019     8  24  15.0 -104.3 38.750
1203677 2019     8  24  15.0 -104.3 38.750
1203678 2019     8  24  14.0 -104.3 38.750
1203679 2019     8  24  14.1 -104.3 38.767
1203680 2019     8  24  13.4 -104.3 38.767
1203681 2019     8  24  13.0 -104.3 38.750
1203682 2019     8  24  12.2 -104.3 38.767
1203683 2019     8  24  12.0 -104.3 38.750
1203684 2019     8  24  12.0 -104.3 38.750
1203685 2019     8  24  13.0 -104.3 38.750
1203686 2019     8  24  13.0 -104.3 38.750
1203687 2019     8  24  13.0 -104.3 38.750
1203688 2019     8  24  13.0 -104.3 38.750
1203689 2019     8  24  13.0 -104.3 38.750
1203690 2019     8  24  13.0 -104.3 38.750
1203691 2019     8  24  13.0 -104.3 38.750
1203692 2019     8  24  12.4 -104.3 38.767
1203693 2019     8  24  12.0 -104.3 38.750
1203694 2019     8  24  12.0 -104.3 38.750
1203695 2019     8  24  12.0 -104.3 38.750
1203696 2019     8  24  12.0 -104.3 38.767
1203697 2019     8  24  13.3 -104.3 38.767
1203698 2019     8  24  15.0 -104.3 38.750
1203699 2019     8  24  15.0 -104.3 38.750
1203700 2019     8  24  15.0 -104.3 38.767
1203701 2019     8  24  16.0 -104.3 38.750
1203702 2019     8  24  16.7 -104.3 38.767
1203703 2019     8  24  19.7 -104.3 38.767
1203704 2019     8  24  22.3 -104.3 38.767
1203705 2019     8  24  25.5 -104.3 38.767
1203706 2019     8  24  26.1 -104.3 38.767
1203707 2019     8  24  26.1 -104.3 38.767
1203708 2019     8  24  26.7 -104.3 38.767
1203709 2019     8  24  25.9 -104.3 38.767
1203710 2019     8  24  25.1 -104.3 38.767
1203711 2019     8  25  23.9 -104.3 38.767
1203712 2019     8  25  20.7 -104.3 38.767
1203713 2019     8  25  18.7 -104.3 38.767
1203714 2019     8  25  16.3 -104.3 38.767
1203715 2019     8  25  14.7 -104.3 38.767
1203716 2019     8  25  14.0 -104.3 38.767
1203717 2019     8  25  13.7 -104.3 38.767
1203719 2019     8  25  13.1 -104.3 38.767
1203720 2019     8  25  12.7 -104.3 38.767
1203721 2019     8  25  13.1 -104.3 38.767
1203722 2019     8  25  12.7 -104.3 38.767
1203723 2019     8  25  13.4 -104.3 38.767
1203724 2019     8  25  14.2 -104.3 38.767
1203725 2019     8  25  19.9 -104.3 38.767
1203726 2019     8  25  25.5 -104.3 38.767
1203727 2019     8  25  28.8 -104.3 38.767
1203728 2019     8  25  30.0 -104.3 38.767
1203729 2019     8  25  30.0 -104.3 38.750
1203730 2019     8  25  30.8 -104.3 38.767
1203731 2019     8  25  30.5 -104.3 38.767
1203732 2019     8  25  31.6 -104.3 38.767
1203733 2019     8  25  32.5 -104.3 38.767
1203734 2019     8  25  32.2 -104.3 38.767
1203735 2019     8  25  32.5 -104.3 38.767
1203736 2019     8  25  32.0 -104.3 38.767
1203737 2019     8  26  31.2 -104.3 38.767
1203738 2019     8  26  25.9 -104.3 38.767
1203739 2019     8  26  24.1 -104.3 38.767
1203740 2019     8  26  22.7 -104.3 38.767
1203741 2019     8  26  21.5 -104.3 38.767
1203742 2019     8  26  16.7 -104.3 38.767
1203743 2019     8  26  15.9 -104.3 38.767
1203744 2019     8  26  14.6 -104.3 38.767
1203745 2019     8  26  18.4 -104.3 38.767
1203746 2019     8  26  19.5 -104.3 38.767
1203747 2019     8  26  15.6 -104.3 38.767
1203748 2019     8  26  16.8 -104.3 38.767
1203749 2019     8  26  14.7 -104.3 38.767
1203750 2019     8  26  16.6 -104.3 38.767
1203751 2019     8  26  19.6 -104.3 38.767
1203752 2019     8  26  21.7 -104.3 38.767
1203753 2019     8  26  22.8 -104.3 38.767
1203754 2019     8  26  23.5 -104.3 38.767
1203755 2019     8  26  24.3 -104.3 38.767
1203756 2019     8  26  25.6 -104.3 38.767
1203757 2019     8  26  25.2 -104.3 38.767
1203758 2019     8  26  25.3 -104.3 38.767
1203759 2019     8  26  24.7 -104.3 38.767
1203760 2019     8  27  23.6 -104.3 38.767
1203761 2019     8  27  20.2 -104.3 38.767
1203762 2019     8  27  19.2 -104.3 38.767
1203763 2019     8  27  17.3 -104.3 38.767
1203764 2019     8  27  16.0 -104.3 38.767
1203765 2019     8  27  15.1 -104.3 38.767
1203766 2019     8  27  13.9 -104.3 38.767
1203767 2019     8  27  13.6 -104.3 38.767
1203768 2019     8  27  14.7 -104.3 38.767
1203769 2019     8  27  14.9 -104.3 38.767
1203770 2019     8  27  15.0 -104.3 38.750
1203771 2019     8  27  14.6 -104.3 38.767
1203772 2019     8  27  14.0 -104.3 38.750
1203773 2019     8  27  13.8 -104.3 38.767
1203774 2019     8  27  14.0 -104.3 38.750
1203775 2019     8  27  13.8 -104.3 38.767
1203776 2019     8  27  15.3 -104.3 38.767
1203777 2019     8  27  17.4 -104.3 38.767
1203778 2019     8  27  18.4 -104.3 38.767
1203779 2019     8  27  19.0 -104.3 38.750
1203780 2019     8  27  19.0 -104.3 38.750
1203781 2019     8  27  19.0 -104.3 38.750
1203782 2019     8  27  19.0 -104.3 38.750
1203783 2019     8  27  19.0 -104.3 38.767
1203784 2019     8  27  19.0 -104.3 38.750
1203785 2019     8  27  20.0 -104.3 38.750
1203786 2019     8  27  20.5 -104.3 38.767
1203787 2019     8  27  21.0 -104.3 38.750
1203788 2019     8  27  21.0 -104.3 38.750
1203789 2019     8  27  20.9 -104.3 38.767
1203790 2019     8  27  22.0 -104.3 38.767
1203791 2019     8  27  22.9 -104.3 38.767
1203792 2019     8  27  23.8 -104.3 38.767
1203793 2019     8  27  24.2 -104.3 38.767
1203794 2019     8  27  24.1 -104.3 38.767
1203795 2019     8  28  22.7 -104.3 38.767
1203796 2019     8  28  20.0 -104.3 38.767
1203797 2019     8  28  18.3 -104.3 38.767
1203798 2019     8  28  17.1 -104.3 38.767
1203799 2019     8  28  15.2 -104.3 38.767
1203800 2019     8  28  14.0 -104.3 38.750
1203801 2019     8  28  13.4 -104.3 38.767
1203802 2019     8  28  13.0 -104.3 38.750
1203803 2019     8  28  13.7 -104.3 38.767
1203804 2019     8  28  14.0 -104.3 38.750
1203805 2019     8  28  14.6 -104.3 38.767
1203806 2019     8  28  15.0 -104.3 38.750
1203807 2019     8  28  14.5 -104.3 38.767
1203808 2019     8  28  15.0 -104.3 38.750
1203809 2019     8  28  14.7 -104.3 38.767
1203810 2019     8  28  15.0 -104.3 38.750
1203811 2019     8  28  15.0 -104.3 38.750
1203812 2019     8  28  15.0 -104.3 38.750
1203813 2019     8  28  15.0 -104.3 38.750
1203814 2019     8  28  14.5 -104.3 38.767
1203815 2019     8  28  14.0 -104.3 38.750
1203816 2019     8  28  14.1 -104.3 38.767
1203817 2019     8  28  14.0 -104.3 38.750
1203818 2019     8  28  14.0 -104.3 38.750
1203819 2019     8  28  14.0 -104.3 38.750
1203820 2019     8  28  13.8 -104.3 38.767
1203821 2019     8  28  14.3 -104.3 38.767
1203822 2019     8  28  15.0 -104.3 38.750
1203823 2019     8  28  15.0 -104.3 38.750
1203824 2019     8  28  15.0 -104.3 38.767
1203825 2019     8  28  15.0 -104.3 38.750
1203826 2019     8  28  17.7 -104.3 38.767
1203827 2019     8  28  22.3 -104.3 38.767
1203828 2019     8  28  24.3 -104.3 38.767
1203829 2019     8  28  26.4 -104.3 38.767
1203830 2019     8  28  29.0 -104.3 38.767
1203831 2019     8  28  29.2 -104.3 38.767
1203832 2019     8  28  30.1 -104.3 38.767
1203833 2019     8  28  30.4 -104.3 38.767
1203834 2019     8  28  29.9 -104.3 38.767
1203835 2019     8  29  27.3 -104.3 38.767
1203836 2019     8  29  21.6 -104.3 38.767
1203837 2019     8  29  21.1 -104.3 38.767
1203838 2019     8  29  18.0 -104.3 38.767
1203839 2019     8  29  20.7 -104.3 38.767
1203840 2019     8  29  15.2 -104.3 38.767
1203841 2019     8  29  15.8 -104.3 38.767
1203843 2019     8  29  14.3 -104.3 38.767
1203844 2019     8  29  14.6 -104.3 38.767
1203845 2019     8  29  15.2 -104.3 38.767
1203846 2019     8  29  14.0 -104.3 38.767
1203847 2019     8  29  13.9 -104.3 38.767
1203848 2019     8  29  14.7 -104.3 38.767
1203849 2019     8  29  19.7 -104.3 38.767
1203850 2019     8  29  25.3 -104.3 38.767
1203851 2019     8  29  29.3 -104.3 38.767
1203852 2019     8  29  31.8 -104.3 38.767
1203853 2019     8  29  32.1 -104.3 38.767
1203854 2019     8  29  31.9 -104.3 38.767
1203855 2019     8  29  32.0 -104.3 38.767
1203856 2019     8  29  32.1 -104.3 38.767
1203857 2019     8  29  30.8 -104.3 38.767
1203858 2019     8  29  30.5 -104.3 38.767
1203859 2019     8  29  32.0 -104.3 38.767
1203860 2019     8  29  31.0 -104.3 38.767
1203861 2019     8  29  30.0 -104.3 38.767
1203862 2019     8  29  29.6 -104.3 38.767
1203863 2019     8  30  26.6 -104.3 38.767
1203864 2019     8  30  22.6 -104.3 38.767
1203865 2019     8  30  22.0 -104.3 38.767
1203866 2019     8  30  20.4 -104.3 38.767
1203867 2019     8  30  20.0 -104.3 38.767
1203868 2019     8  30  18.3 -104.3 38.767
1203869 2019     8  30  16.7 -104.3 38.767
1203870 2019     8  30  16.5 -104.3 38.767
1203871 2019     8  30  15.6 -104.3 38.767
1203872 2019     8  30  12.9 -104.3 38.767
1203873 2019     8  30  14.2 -104.3 38.767
1203874 2019     8  30  12.5 -104.3 38.767
1203875 2019     8  30  13.9 -104.3 38.767
1203876 2019     8  30  15.4 -104.3 38.767
1203877 2019     8  30  15.0 -104.3 38.767
1203878 2019     8  30  13.0 -104.3 38.767
1203879 2019     8  30  13.0 -104.3 38.767
1203880 2019     8  30  13.0 -104.3 38.767
1203881 2019     8  30  13.0 -104.3 38.767
1203882 2019     8  30  14.0 -104.3 38.767
1203883 2019     8  30  14.0 -104.3 38.767
1203884 2019     8  30  14.0 -104.3 38.767
1203885 2019     8  30  15.2 -104.3 38.767
1203886 2019     8  30  19.1 -104.3 38.767
1203887 2019     8  30  20.7 -104.3 38.767
1203888 2019     8  30  22.6 -104.3 38.767
1203889 2019     8  30  24.1 -104.3 38.767
1203890 2019     8  30  25.7 -104.3 38.767
1203891 2019     8  30  25.5 -104.3 38.767
1203892 2019     8  30  25.4 -104.3 38.767
1203893 2019     8  30  25.3 -104.3 38.767
1203894 2019     8  30  24.0 -104.3 38.750
1203895 2019     8  30  23.8 -104.3 38.750
1203896 2019     8  30  24.0 -104.3 38.750
1203897 2019     8  31  21.9 -104.3 38.767
1203898 2019     8  31  19.3 -104.3 38.767
1203899 2019     8  31  18.1 -104.3 38.767
1203900 2019     8  31  17.7 -104.3 38.767
1203901 2019     8  31  15.9 -104.3 38.767
1203902 2019     8  31  16.8 -104.3 38.767
1203903 2019     8  31  14.1 -104.3 38.767
1203905 2019     8  31  13.1 -104.3 38.767
1203906 2019     8  31  14.8 -104.3 38.767
1203907 2019     8  31  15.0 -104.3 38.767
1203908 2019     8  31  15.0 -104.3 38.767
1203909 2019     8  31  14.5 -104.3 38.767
1203910 2019     8  31  14.0 -104.3 38.767
1203911 2019     8  31  15.3 -104.3 38.767
1203912 2019     8  31  15.0 -104.3 38.767
1203913 2019     8  31  15.0 -104.3 38.767
1203914 2019     8  31  14.7 -104.3 38.767
1203915 2019     8  31  14.9 -104.3 38.767
1203916 2019     8  31  15.0 -104.3 38.767
1203917 2019     8  31  15.0 -104.3 38.767
1203918 2019     8  31  15.0 -104.3 38.767
1203919 2019     8  31  16.0 -104.3 38.767
1203920 2019     8  31  15.9 -104.3 38.767
1203921 2019     8  31  16.7 -104.3 38.767
1203922 2019     8  31  19.2 -104.3 38.767
1203923 2019     8  31  23.1 -104.3 38.767
1203924 2019     8  31  25.5 -104.3 38.767
1203925 2019     8  31  26.8 -104.3 38.767
1203926 2019     8  31  28.9 -104.3 38.767
1203927 2019     8  31  26.0 -104.3 38.767
1203928 2019     8  31  26.0 -104.3 38.767
1203929 2019     8  31  25.6 -104.3 38.767
1203930 2019     8  31  26.0 -104.3 38.767
1203931 2019     8  31  23.0 -104.3 38.767
1203932 2019     8  31  24.0 -104.3 38.767
1203933 2019     8  31  26.1 -104.3 38.750
1203934 2019     8  31  26.3 -104.3 38.750</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>tx <span class="ot">&lt;-</span> met[met<span class="sc">$</span>lon <span class="sc">==</span> <span class="sc">-</span><span class="fl">98.052</span>,<span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'month'</span>,<span class="st">'day'</span>,<span class="st">'temp'</span>,<span class="st">'lon'</span>,<span class="st">'lat'</span>)]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>tx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        year month day  temp     lon    lat
1105137 2019     8   1  31.1 -98.052 27.901
1105140 2019     8   1  27.2 -98.052 27.901
1105141 2019     8   1  27.2 -98.052 27.901
1105142 2019     8   1  26.7 -98.052 27.901
1105146 2019     8   1  25.0 -98.052 27.901
1105147 2019     8   1  24.4 -98.052 27.901
1105154 2019     8   1  34.4 -98.052 27.901
1105364 2019     8   9  27.2 -98.052 27.901
1105365 2019     8   9  27.2 -98.052 27.901
1105455 2019     8  11 -17.0 -98.052 27.901
1105457 2019     8  12 -17.0 -98.052 27.901
1105459 2019     8  12 -17.0 -98.052 27.901
1105464 2019     8  12  27.8 -98.052 27.901
1105465 2019     8  12  26.7 -98.052 27.901
1105466 2019     8  12  26.1 -98.052 27.901
1105467 2019     8  12  26.1 -98.052 27.901
1105468 2019     8  12  26.1 -98.052 27.901
1105469 2019     8  12  25.6 -98.052 27.901
1105470 2019     8  12  25.6 -98.052 27.901
1105471 2019     8  12  26.1 -98.052 27.901
1105472 2019     8  12  26.1 -98.052 27.901
1105473 2019     8  12  25.6 -98.052 27.901
1105474 2019     8  12  26.7 -98.052 27.901
1105475 2019     8  12  28.9 -98.052 27.901
1105476 2019     8  12  29.4 -98.052 27.901
1105477 2019     8  12  30.0 -98.052 27.901
1105496 2019     8  13  27.2 -98.052 27.901
1105551 2019     8  15  26.1 -98.052 27.901
1106013 2019     8  31  32.8 -98.052 27.901
1106014 2019     8  31  32.8 -98.052 27.901
1106015 2019     8  31  32.2 -98.052 27.901</code></pre>
</div>
</div>
<p>For both weather stations with temperatures of -17, these values are highly different from readings on surrounding days. For the Colorado station, it is possible that the negative sign is the only mistake (should be +17.2) but we cannot confirm this, so I will remove all values less than -10.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>met <span class="ot">&lt;-</span> met[met<span class="sc">$</span>temp<span class="sc">&gt;-</span><span class="dv">10</span>,]</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(met<span class="sc">$</span>temp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  -3.00   19.60   23.50   23.59   27.80   56.00 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>low_elev <span class="ot">&lt;-</span> met[met<span class="sc">$</span>elev<span class="sc">&lt;</span><span class="dv">0</span>,<span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'month'</span>,<span class="st">'day'</span>,<span class="st">'elev'</span>,<span class="st">'lon'</span>,<span class="st">'lat'</span>)]</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(low_elev)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      year          month          day             elev             lon        
 Min.   :2019   Min.   :8     Min.   : 1.00   Min.   :-13.00   Min.   :-115.7  
 1st Qu.:2019   1st Qu.:8     1st Qu.: 8.00   1st Qu.:-12.00   1st Qu.:-115.7  
 Median :2019   Median :8     Median :16.00   Median :-12.00   Median :-115.7  
 Mean   :2019   Mean   :8     Mean   :15.99   Mean   :-12.01   Mean   :-115.7  
 3rd Qu.:2019   3rd Qu.:8     3rd Qu.:24.00   3rd Qu.:-12.00   3rd Qu.:-115.7  
 Max.   :2019   Max.   :8     Max.   :31.00   Max.   :-12.00   Max.   :-115.7  
 NA's   :182    NA's   :182   NA's   :182     NA's   :182      NA's   :182     
      lat       
 Min.   :32.82  
 1st Qu.:32.82  
 Median :32.82  
 Mean   :32.82  
 3rd Qu.:32.82  
 Max.   :32.83  
 NA's   :182    </code></pre>
</div>
</div>
<p>There is one weather station with elevation below 0 at (32.83, -115.7). This is in Southern California, in the Imperial Valley which is below sea level, so this makes sense.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>high_elev <span class="ot">&lt;-</span> met[met<span class="sc">$</span>elev<span class="sc">&gt;</span><span class="dv">4000</span>,<span class="fu">c</span>(<span class="st">'year'</span>,<span class="st">'month'</span>,<span class="st">'day'</span>,<span class="st">'elev'</span>,<span class="st">'lon'</span>,<span class="st">'lat'</span>,<span class="st">'wind.sp'</span>,<span class="st">'temp'</span>,<span class="st">'hour'</span>)]</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>high_elev <span class="ot">&lt;-</span> high_elev[<span class="sc">!</span><span class="fu">is.na</span>(high_elev<span class="sc">$</span>elev),]</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(high_elev)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      year          month        day            elev           lon        
 Min.   :2019   Min.   :8   Min.   : 1.0   Min.   :4113   Min.   :-105.8  
 1st Qu.:2019   1st Qu.:8   1st Qu.: 8.0   1st Qu.:4113   1st Qu.:-105.8  
 Median :2019   Median :8   Median :16.0   Median :4113   Median :-105.8  
 Mean   :2019   Mean   :8   Mean   :16.1   Mean   :4113   Mean   :-105.8  
 3rd Qu.:2019   3rd Qu.:8   3rd Qu.:24.0   3rd Qu.:4113   3rd Qu.:-105.8  
 Max.   :2019   Max.   :8   Max.   :31.0   Max.   :4113   Max.   :-105.8  
                                                                          
      lat          wind.sp            temp            hour      
 Min.   :39.8   Min.   : 0.000   Min.   : 1.00   Min.   : 0.00  
 1st Qu.:39.8   1st Qu.: 4.100   1st Qu.: 6.00   1st Qu.: 6.00  
 Median :39.8   Median : 6.700   Median : 8.00   Median :12.00  
 Mean   :39.8   Mean   : 7.245   Mean   : 8.13   Mean   :11.66  
 3rd Qu.:39.8   3rd Qu.: 9.800   3rd Qu.:10.00   3rd Qu.:18.00  
 Max.   :39.8   Max.   :21.100   Max.   :15.00   Max.   :23.00  
                NA's   :168                                     </code></pre>
</div>
</div>
<p>There is one weather station with elevation above 4000m at (39.8, -105.8). This is in a mountainous area in Colorado where the elevation is this high, so this makes sense</p>
</section>
<section id="summary-stats" class="level3">
<h3 class="anchored" data-anchor-id="summary-stats">6. Summary Stats</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>high_elev <span class="ot">&lt;-</span> high_elev[<span class="sc">!</span><span class="fu">is.na</span>(high_elev<span class="sc">$</span>wind.sp),]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(high_elev)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      year          month        day             elev           lon        
 Min.   :2019   Min.   :8   Min.   : 1.00   Min.   :4113   Min.   :-105.8  
 1st Qu.:2019   1st Qu.:8   1st Qu.: 8.00   1st Qu.:4113   1st Qu.:-105.8  
 Median :2019   Median :8   Median :16.00   Median :4113   Median :-105.8  
 Mean   :2019   Mean   :8   Mean   :16.02   Mean   :4113   Mean   :-105.8  
 3rd Qu.:2019   3rd Qu.:8   3rd Qu.:24.00   3rd Qu.:4113   3rd Qu.:-105.8  
 Max.   :2019   Max.   :8   Max.   :31.00   Max.   :4113   Max.   :-105.8  
      lat          wind.sp            temp             hour      
 Min.   :39.8   Min.   : 0.000   Min.   : 1.000   Min.   : 0.00  
 1st Qu.:39.8   1st Qu.: 4.100   1st Qu.: 6.000   1st Qu.: 6.00  
 Median :39.8   Median : 6.700   Median : 8.000   Median :12.00  
 Mean   :39.8   Mean   : 7.245   Mean   : 8.135   Mean   :11.69  
 3rd Qu.:39.8   3rd Qu.: 9.800   3rd Qu.:10.000   3rd Qu.:18.00  
 Max.   :39.8   Max.   :21.100   Max.   :15.000   Max.   :23.00  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(high_elev[,<span class="fu">c</span>(<span class="st">'day'</span>,<span class="st">'hour'</span>,<span class="st">'temp'</span>,<span class="st">'wind.sp'</span>)])</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>cor_matrix </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 day         hour         temp     wind.sp
day      1.000000000 -0.004546462 -0.006130763  0.36430791
hour    -0.004546462  1.000000000  0.435680110  0.08807315
temp    -0.006130763  0.435680110  1.000000000 -0.09373843
wind.sp  0.364307915  0.088073152 -0.093738431  1.00000000</code></pre>
</div>
</div>
<p>There is not a strong linear correlation between day and hour or temp, and between hour and temp. There appears to be a moderate correlation between hour and temperature (r=0.435) and day and windspeed (r=0.364). However, this is only looking at linear relationships and does not address the fact that temperatures generally follow day long cycles (warmest mid-day).</p>
</section>
<section id="exploratory-graphs" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-graphs">7. Exploratory Graphs</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leaflet</span>(high_elev) <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addProviderTiles</span>(<span class="st">'OpenStreetMap'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addCircles</span>(<span class="at">lat=</span><span class="sc">~</span>lat,<span class="at">lng=</span><span class="sc">~</span>lon, <span class="at">opacity=</span><span class="dv">1</span>, <span class="at">fillOpacity=</span><span class="dv">1</span>, <span class="at">radius=</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="leaflet html-widget html-fill-item" id="htmlwidget-4d9d259f21bd768742e3" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-4d9d259f21bd768742e3">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["OpenStreetMap",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircles","args":[[39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8,39.8],[-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766,-105.766],100,null,null,{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":1,"fill":true,"fillColor":"#03F","fillOpacity":1},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]}],"limits":{"lat":[39.8,39.8],"lng":[-105.766,-105.766]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>high_elev<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">with</span>(high_elev, <span class="fu">ymd_h</span>(<span class="fu">paste</span>(year, month, day, hour, <span class="at">sep=</span> <span class="st">' '</span>)))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(high_elev<span class="sc">$</span>date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Min.               1st Qu.                Median 
"2019-08-01 00:00:00" "2019-08-08 06:00:00" "2019-08-16 17:00:00" 
                 Mean               3rd Qu.                  Max. 
"2019-08-16 12:13:41" "2019-08-24 13:00:00" "2019-08-31 22:00:00" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>high_elev <span class="ot">&lt;-</span> high_elev[<span class="fu">order</span>(high_elev<span class="sc">$</span>date), ]</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(high_elev)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       year month day elev      lon  lat wind.sp temp hour                date
221697 2019     8   1 4113 -105.766 39.8     8.8    9    0 2019-08-01 00:00:00
221698 2019     8   1 4113 -105.766 39.8     2.6    9    0 2019-08-01 00:00:00
221699 2019     8   1 4113 -105.766 39.8     3.1    9    1 2019-08-01 01:00:00
221700 2019     8   1 4113 -105.766 39.8     4.1    9    1 2019-08-01 01:00:00
221701 2019     8   1 4113 -105.766 39.8     4.6    9    1 2019-08-01 01:00:00
221702 2019     8   1 4113 -105.766 39.8     6.2    9    2 2019-08-01 02:00:00</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(high_elev<span class="sc">$</span>date,high_elev<span class="sc">$</span>temp,<span class="at">xlab=</span><span class="st">'Date'</span>,<span class="at">ylab=</span><span class="st">'Temperature (˚C)'</span>,<span class="at">main=</span><span class="st">'Temperature at Highest Elevation'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(high_elev<span class="sc">$</span>date,high_elev<span class="sc">$</span>wind.sp,<span class="at">xlab=</span><span class="st">'Date'</span>,<span class="at">ylab=</span><span class="st">'Windspeed'</span>,<span class="at">main=</span><span class="st">'Windspeed at Highest Elevation'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There is not a clear trend between date and temperature or windspeed. High values tend to be pooled together, so it is not completely random.</p>
</section>
<section id="ask-questions" class="level3">
<h3 class="anchored" data-anchor-id="ask-questions">8. Ask Questions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>met_daily <span class="ot">&lt;-</span> <span class="fu">summarize</span>(met,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">temp=</span><span class="fu">min</span>(temp),</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">elev=</span><span class="fu">mean</span>(elev),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">.by =</span> <span class="fu">c</span>(USAFID,day))</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(met_daily)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     USAFID            day          temp            elev        
 Min.   :690150   Min.   : 1   Min.   :-3.00   Min.   : -12.21  
 1st Qu.:722124   1st Qu.: 8   1st Qu.:15.00   1st Qu.:  90.00  
 Median :723320   Median :16   Median :19.00   Median : 240.00  
 Mean   :723409   Mean   :16   Mean   :18.64   Mean   : 416.66  
 3rd Qu.:725146   3rd Qu.:24   3rd Qu.:22.80   3rd Qu.: 404.00  
 Max.   :726813   Max.   :31   Max.   :41.00   Max.   :4113.00  
                                               NA's   :182      </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>met_daily <span class="ot">&lt;-</span> met_daily[<span class="sc">!</span><span class="fu">is.na</span>(met_daily<span class="sc">$</span>temp),]</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(temp <span class="sc">~</span> elev, <span class="at">data =</span> met_daily)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(temp <span class="sc">~</span> elev, <span class="at">data =</span> met_daily,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.5</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Daily Low Temperature and Elevation"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Elevation"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Daily Low Temperature (°C)"</span>)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = temp ~ elev, data = met_daily)

Residuals:
    Min      1Q  Median      3Q     Max 
-20.265  -3.067   0.459   3.316  23.689 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.040e+01  2.617e-02   779.6   &lt;2e-16 ***
elev        -4.188e-03  3.792e-05  -110.4   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.595 on 48534 degrees of freedom
  (182 observations deleted due to missingness)
Multiple R-squared:  0.2008,    Adjusted R-squared:  0.2008 
F-statistic: 1.22e+04 on 1 and 48534 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There is a negative association between elevation and daily low temperature. Stations at are expected to have about a 4.188 degree lower daily low for every 1000 meters higer in elevation</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>